name: Nightly Update to Data Display

on:
  schedule:
    - cron:  '0 21 * * *'

env:
  root: "S3/eictest/EPIC/RECO/"

jobs:
  update_data:
    runs-on: ubuntu-latest
    container:
      image: minio/mc:latest
    steps:
    - name: Search the database and save the file names as a list
      shell: bash
      run: |
        mc config host add S3 ${S3_HOST} ${S3_ACCESS_KEY} ${S3_SECRET_KEY}
        ./list_s3.sh > s3_objects.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add s3_objects.txt
        git commit -m "Update list in s3_objects.txt" || echo "No changes to commit"
      env:
        S3_HOST: ${{secrets.S3_HOST}}
        S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
        S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}

  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@2.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
